# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\FigUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(846, 810)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 391, 361))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayoutTrainFig1 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayoutTrainFig1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutTrainFig1.setObjectName("verticalLayoutTrainFig1")
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(440, 20, 391, 361))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayoutTrainFig2 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayoutTrainFig2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutTrainFig2.setObjectName("verticalLayoutTrainFig2")
        self.layoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 400, 411, 401))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayoutTrainFig3 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayoutTrainFig3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutTrainFig3.setObjectName("verticalLayoutTrainFig3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
