# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui\mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 495)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 471, 481))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPredict = QtWidgets.QWidget()
        self.tabPredict.setObjectName("tabPredict")
        self.label = QtWidgets.QLabel(self.tabPredict)
        self.label.setGeometry(QtCore.QRect(11, 20, 37, 16))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.comboBoxModels = QtWidgets.QComboBox(self.tabPredict)
        self.comboBoxModels.setGeometry(QtCore.QRect(50, 21, 191, 20))
        self.comboBoxModels.setCurrentText("")
        self.comboBoxModels.setObjectName("comboBoxModels")
        self.pushButtonLoadModel = QtWidgets.QPushButton(self.tabPredict)
        self.pushButtonLoadModel.setGeometry(QtCore.QRect(260, 20, 31, 23))
        self.pushButtonLoadModel.setObjectName("pushButtonLoadModel")
        self.groupBox = QtWidgets.QGroupBox(self.tabPredict)
        self.groupBox.setGeometry(QtCore.QRect(0, 60, 271, 121))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 231, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButtonDataUpload = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonDataUpload.setGeometry(QtCore.QRect(10, 20, 82, 21))
        self.radioButtonDataUpload.setChecked(True)
        self.radioButtonDataUpload.setObjectName("radioButtonDataUpload")
        self.radioButtonDataTable = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonDataTable.setGeometry(QtCore.QRect(10, 40, 82, 31))
        self.radioButtonDataTable.setObjectName("radioButtonDataTable")
        self.pushButtonLoadDataFile = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonLoadDataFile.setEnabled(True)
        self.pushButtonLoadDataFile.setGeometry(QtCore.QRect(100, 20, 31, 23))
        self.pushButtonLoadDataFile.setObjectName("pushButtonLoadDataFile")
        self.checkBoxWithHeader = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxWithHeader.setGeometry(QtCore.QRect(140, 20, 81, 17))
        self.checkBoxWithHeader.setObjectName("checkBoxWithHeader")
        self.pushButtonLoadData = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonLoadData.setEnabled(True)
        self.pushButtonLoadData.setGeometry(QtCore.QRect(190, 90, 61, 23))
        self.pushButtonLoadData.setObjectName("pushButtonLoadData")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabPredict)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 50, 161, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lcdNumberPredictedTemperature = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumberPredictedTemperature.setEnabled(True)
        self.lcdNumberPredictedTemperature.setGeometry(QtCore.QRect(1, 21, 131, 71))
        self.lcdNumberPredictedTemperature.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberPredictedTemperature.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberPredictedTemperature.setSmallDecimalPoint(True)
        self.lcdNumberPredictedTemperature.setDigitCount(5)
        self.lcdNumberPredictedTemperature.setProperty("value", 8.0)
        self.lcdNumberPredictedTemperature.setProperty("intValue", 8)
        self.lcdNumberPredictedTemperature.setObjectName("lcdNumberPredictedTemperature")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(128, 21, 32, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButtonPredict = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonPredict.setGeometry(QtCore.QRect(40, 90, 75, 23))
        self.pushButtonPredict.setObjectName("pushButtonPredict")
        self.labelModelFileName = QtWidgets.QLabel(self.tabPredict)
        self.labelModelFileName.setGeometry(QtCore.QRect(310, 20, 121, 16))
        self.labelModelFileName.setObjectName("labelModelFileName")
        self.tableWidgetData = QtWidgets.QTableWidget(self.tabPredict)
        self.tableWidgetData.setGeometry(QtCore.QRect(20, 200, 411, 251))
        self.tableWidgetData.setAlternatingRowColors(True)
        self.tableWidgetData.setRowCount(11)
        self.tableWidgetData.setColumnCount(2)
        self.tableWidgetData.setObjectName("tableWidgetData")
        self.tableWidgetData.horizontalHeader().setVisible(False)
        self.tableWidgetData.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetData.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidgetData.horizontalHeader().setMinimumSectionSize(70)
        self.tableWidgetData.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetData.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetData.verticalHeader().setDefaultSectionSize(30)
        self.labelDataFileName = QtWidgets.QLabel(self.tabPredict)
        self.labelDataFileName.setGeometry(QtCore.QRect(20, 180, 211, 16))
        self.labelDataFileName.setObjectName("labelDataFileName")
        self.tabWidget.addTab(self.tabPredict, "")
        self.tabTrain_Valid = QtWidgets.QWidget()
        self.tabTrain_Valid.setObjectName("tabTrain_Valid")
        self.comboBoxTrainModels = QtWidgets.QComboBox(self.tabTrain_Valid)
        self.comboBoxTrainModels.setEnabled(True)
        self.comboBoxTrainModels.setGeometry(QtCore.QRect(50, 21, 191, 20))
        self.comboBoxTrainModels.setCurrentText("")
        self.comboBoxTrainModels.setObjectName("comboBoxTrainModels")
        self.label_2 = QtWidgets.QLabel(self.tabTrain_Valid)
        self.label_2.setGeometry(QtCore.QRect(11, 20, 37, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.labelTrainModelFileName = QtWidgets.QLabel(self.tabTrain_Valid)
        self.labelTrainModelFileName.setGeometry(QtCore.QRect(310, 20, 121, 16))
        self.labelTrainModelFileName.setObjectName("labelTrainModelFileName")
        self.pushButtonTrainLoadModel = QtWidgets.QPushButton(self.tabTrain_Valid)
        self.pushButtonTrainLoadModel.setEnabled(True)
        self.pushButtonTrainLoadModel.setGeometry(QtCore.QRect(260, 20, 31, 23))
        self.pushButtonTrainLoadModel.setObjectName("pushButtonTrainLoadModel")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabTrain_Valid)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 50, 411, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBoxTrainEpochNum = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxTrainEpochNum.setEnabled(True)
        self.spinBoxTrainEpochNum.setMaximum(500)
        self.spinBoxTrainEpochNum.setProperty("value", 100)
        self.spinBoxTrainEpochNum.setObjectName("spinBoxTrainEpochNum")
        self.horizontalLayout.addWidget(self.spinBoxTrainEpochNum)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.doubleSpinBoxTrainLearningRate = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxTrainLearningRate.setEnabled(True)
        self.doubleSpinBoxTrainLearningRate.setSuffix("")
        self.doubleSpinBoxTrainLearningRate.setDecimals(2)
        self.doubleSpinBoxTrainLearningRate.setMaximum(1.0)
        self.doubleSpinBoxTrainLearningRate.setProperty("value", 0.01)
        self.doubleSpinBoxTrainLearningRate.setObjectName("doubleSpinBoxTrainLearningRate")
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxTrainLearningRate)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBoxTrainBatchSize = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxTrainBatchSize.setEnabled(True)
        self.spinBoxTrainBatchSize.setMaximum(500)
        self.spinBoxTrainBatchSize.setProperty("value", 32)
        self.spinBoxTrainBatchSize.setObjectName("spinBoxTrainBatchSize")
        self.horizontalLayout_2.addWidget(self.spinBoxTrainBatchSize)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.doubleSpinBoxTrainValidationSplit = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxTrainValidationSplit.setEnabled(True)
        self.doubleSpinBoxTrainValidationSplit.setDecimals(1)
        self.doubleSpinBoxTrainValidationSplit.setMaximum(100.0)
        self.doubleSpinBoxTrainValidationSplit.setProperty("value", 10.0)
        self.doubleSpinBoxTrainValidationSplit.setObjectName("doubleSpinBoxTrainValidationSplit")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxTrainValidationSplit)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.doubleSpinBoxTrainSplitRate = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxTrainSplitRate.setEnabled(True)
        self.doubleSpinBoxTrainSplitRate.setSuffix("")
        self.doubleSpinBoxTrainSplitRate.setDecimals(2)
        self.doubleSpinBoxTrainSplitRate.setMaximum(1.0)
        self.doubleSpinBoxTrainSplitRate.setProperty("value", 0.3)
        self.doubleSpinBoxTrainSplitRate.setObjectName("doubleSpinBoxTrainSplitRate")
        self.horizontalLayout_5.addWidget(self.doubleSpinBoxTrainSplitRate)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabTrain_Valid)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 180, 411, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButtonTrainLoadDataFile = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonTrainLoadDataFile.setEnabled(True)
        self.pushButtonTrainLoadDataFile.setGeometry(QtCore.QRect(220, 30, 111, 23))
        self.pushButtonTrainLoadDataFile.setObjectName("pushButtonTrainLoadDataFile")
        self.checkBoxTrainWithHeader = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBoxTrainWithHeader.setEnabled(True)
        self.checkBoxTrainWithHeader.setGeometry(QtCore.QRect(330, 10, 81, 17))
        self.checkBoxTrainWithHeader.setObjectName("checkBoxTrainWithHeader")
        self.pushButtonTrainLoadData = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonTrainLoadData.setEnabled(True)
        self.pushButtonTrainLoadData.setGeometry(QtCore.QRect(340, 30, 61, 23))
        self.pushButtonTrainLoadData.setObjectName("pushButtonTrainLoadData")
        self.labelTrainDataFileName = QtWidgets.QLabel(self.groupBox_5)
        self.labelTrainDataFileName.setGeometry(QtCore.QRect(10, 30, 211, 16))
        self.labelTrainDataFileName.setObjectName("labelTrainDataFileName")
        self.progressBarTrain = QtWidgets.QProgressBar(self.tabTrain_Valid)
        self.progressBarTrain.setGeometry(QtCore.QRect(60, 360, 361, 23))
        self.progressBarTrain.setProperty("value", 0)
        self.progressBarTrain.setObjectName("progressBarTrain")
        self.layoutWidget = QtWidgets.QWidget(self.tabTrain_Valid)
        self.layoutWidget.setGeometry(QtCore.QRect(71, 259, 311, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonTrain = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonTrain.setEnabled(True)
        self.pushButtonTrain.setObjectName("pushButtonTrain")
        self.gridLayout.addWidget(self.pushButtonTrain, 0, 0, 1, 1)
        self.checkBoxTrainReinitWeights = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxTrainReinitWeights.setObjectName("checkBoxTrainReinitWeights")
        self.gridLayout.addWidget(self.checkBoxTrainReinitWeights, 0, 1, 1, 1)
        self.pushButtonValid = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonValid.setEnabled(True)
        self.pushButtonValid.setObjectName("pushButtonValid")
        self.gridLayout.addWidget(self.pushButtonValid, 0, 2, 1, 1)
        self.pushButtonTrainSaveModel = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonTrainSaveModel.setEnabled(True)
        self.pushButtonTrainSaveModel.setObjectName("pushButtonTrainSaveModel")
        self.gridLayout.addWidget(self.pushButtonTrainSaveModel, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabTrain_Valid, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxModels.setCurrentIndex(-1)
        self.comboBoxTrainModels.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBoxModels, self.pushButtonLoadModel)
        Dialog.setTabOrder(self.pushButtonLoadModel, self.tableWidgetData)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RadLab: AI Temperature Predication"))
        self.label.setText(_translate("Dialog", "Models:"))
        self.pushButtonLoadModel.setText(_translate("Dialog", "..."))
        self.groupBox.setTitle(_translate("Dialog", "Input Data"))
        self.groupBox_3.setTitle(_translate("Dialog", "Type of  Data"))
        self.radioButtonDataUpload.setText(_translate("Dialog", "Upload Data"))
        self.radioButtonDataTable.setText(_translate("Dialog", "Table"))
        self.pushButtonLoadDataFile.setText(_translate("Dialog", "..."))
        self.checkBoxWithHeader.setText(_translate("Dialog", "With Header"))
        self.pushButtonLoadData.setText(_translate("Dialog", "Load"))
        self.groupBox_2.setTitle(_translate("Dialog", "Predicted Temperature "))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>[<span style=\" vertical-align:super;\">o</span>C]</p></body></html>"))
        self.pushButtonPredict.setText(_translate("Dialog", "Predict"))
        self.labelModelFileName.setText(_translate("Dialog", "Filename"))
        self.labelDataFileName.setText(_translate("Dialog", "Filename"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPredict), _translate("Dialog", "Predict"))
        self.label_2.setText(_translate("Dialog", "Models:"))
        self.labelTrainModelFileName.setText(_translate("Dialog", "Filename"))
        self.pushButtonTrainLoadModel.setText(_translate("Dialog", "..."))
        self.groupBox_4.setTitle(_translate("Dialog", "Train Prameters"))
        self.label_4.setText(_translate("Dialog", "epoch #"))
        self.label_7.setText(_translate("Dialog", "learning Rate"))
        self.label_5.setText(_translate("Dialog", "batch size"))
        self.label_6.setText(_translate("Dialog", "Validation split"))
        self.doubleSpinBoxTrainValidationSplit.setSuffix(_translate("Dialog", "[%]"))
        self.label_8.setText(_translate("Dialog", "Split rate"))
        self.groupBox_5.setTitle(_translate("Dialog", "Dataset"))
        self.pushButtonTrainLoadDataFile.setText(_translate("Dialog", "Select Data File"))
        self.checkBoxTrainWithHeader.setText(_translate("Dialog", "With Header"))
        self.pushButtonTrainLoadData.setText(_translate("Dialog", "Load"))
        self.labelTrainDataFileName.setText(_translate("Dialog", "Name:"))
        self.pushButtonTrain.setText(_translate("Dialog", "Train"))
        self.checkBoxTrainReinitWeights.setText(_translate("Dialog", "Reset Weights"))
        self.pushButtonValid.setText(_translate("Dialog", "Valid"))
        self.pushButtonTrainSaveModel.setText(_translate("Dialog", "Save Model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTrain_Valid), _translate("Dialog", "Train/Valid"))

