# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui\mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(459, 492)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 441, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPredict = QtWidgets.QWidget()
        self.tabPredict.setObjectName("tabPredict")
        self.label = QtWidgets.QLabel(self.tabPredict)
        self.label.setGeometry(QtCore.QRect(11, 20, 37, 16))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.comboBoxModels = QtWidgets.QComboBox(self.tabPredict)
        self.comboBoxModels.setGeometry(QtCore.QRect(50, 21, 191, 20))
        self.comboBoxModels.setCurrentText("")
        self.comboBoxModels.setObjectName("comboBoxModels")
        self.pushButtonLoadModel = QtWidgets.QPushButton(self.tabPredict)
        self.pushButtonLoadModel.setGeometry(QtCore.QRect(260, 20, 31, 23))
        self.pushButtonLoadModel.setObjectName("pushButtonLoadModel")
        self.groupBox = QtWidgets.QGroupBox(self.tabPredict)
        self.groupBox.setGeometry(QtCore.QRect(0, 60, 261, 381))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 231, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButtonDataUpload = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonDataUpload.setGeometry(QtCore.QRect(10, 20, 82, 21))
        self.radioButtonDataUpload.setChecked(True)
        self.radioButtonDataUpload.setObjectName("radioButtonDataUpload")
        self.radioButtonDataTable = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonDataTable.setGeometry(QtCore.QRect(10, 40, 82, 31))
        self.radioButtonDataTable.setObjectName("radioButtonDataTable")
        self.pushButtonLoadData = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonLoadData.setEnabled(True)
        self.pushButtonLoadData.setGeometry(QtCore.QRect(100, 20, 31, 23))
        self.pushButtonLoadData.setObjectName("pushButtonLoadData")
        self.checkBoxWithHeader = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBoxWithHeader.setGeometry(QtCore.QRect(140, 20, 81, 17))
        self.checkBoxWithHeader.setObjectName("checkBoxWithHeader")
        self.tableWidgetData = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidgetData.setGeometry(QtCore.QRect(20, 120, 231, 251))
        self.tableWidgetData.setRowCount(11)
        self.tableWidgetData.setColumnCount(2)
        self.tableWidgetData.setObjectName("tableWidgetData")
        self.tableWidgetData.horizontalHeader().setVisible(True)
        self.tableWidgetData.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetData.horizontalHeader().setDefaultSectionSize(70)
        self.tableWidgetData.horizontalHeader().setMinimumSectionSize(70)
        self.tableWidgetData.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetData.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetData.verticalHeader().setDefaultSectionSize(30)
        self.labelDataFileName = QtWidgets.QLabel(self.groupBox)
        self.labelDataFileName.setGeometry(QtCore.QRect(20, 100, 211, 16))
        self.labelDataFileName.setObjectName("labelDataFileName")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabPredict)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 60, 161, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lcdNumberPredictedTemperature = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumberPredictedTemperature.setEnabled(True)
        self.lcdNumberPredictedTemperature.setGeometry(QtCore.QRect(1, 21, 131, 71))
        self.lcdNumberPredictedTemperature.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumberPredictedTemperature.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumberPredictedTemperature.setSmallDecimalPoint(True)
        self.lcdNumberPredictedTemperature.setDigitCount(5)
        self.lcdNumberPredictedTemperature.setProperty("value", 8.0)
        self.lcdNumberPredictedTemperature.setProperty("intValue", 8)
        self.lcdNumberPredictedTemperature.setObjectName("lcdNumberPredictedTemperature")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(128, 21, 32, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButtonPredict = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonPredict.setGeometry(QtCore.QRect(50, 110, 75, 23))
        self.pushButtonPredict.setObjectName("pushButtonPredict")
        self.labelModelFileName = QtWidgets.QLabel(self.tabPredict)
        self.labelModelFileName.setGeometry(QtCore.QRect(310, 20, 121, 16))
        self.labelModelFileName.setObjectName("labelModelFileName")
        self.tabWidget.addTab(self.tabPredict, "")
        self.tabTrain = QtWidgets.QWidget()
        self.tabTrain.setObjectName("tabTrain")
        self.layoutWidget = QtWidgets.QWidget(self.tabTrain)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 120, 191, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxShowPerformance = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBoxShowPerformance.setObjectName("checkBoxShowPerformance")
        self.verticalLayout_2.addWidget(self.checkBoxShowPerformance)
        self.verticalLayoutFigure = QtWidgets.QVBoxLayout()
        self.verticalLayoutFigure.setObjectName("verticalLayoutFigure")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutFigure.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayoutFigure)
        self.tabWidget.addTab(self.tabTrain, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxModels.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBoxModels, self.pushButtonLoadModel)
        Dialog.setTabOrder(self.pushButtonLoadModel, self.tableWidgetData)
        Dialog.setTabOrder(self.tableWidgetData, self.tabWidget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RadLab: AI Temperature Predication"))
        self.label.setText(_translate("Dialog", "Models:"))
        self.pushButtonLoadModel.setText(_translate("Dialog", "..."))
        self.groupBox.setTitle(_translate("Dialog", "Input Data"))
        self.groupBox_3.setTitle(_translate("Dialog", "Type of  Data"))
        self.radioButtonDataUpload.setText(_translate("Dialog", "Upload Data"))
        self.radioButtonDataTable.setText(_translate("Dialog", "Table"))
        self.pushButtonLoadData.setText(_translate("Dialog", "..."))
        self.checkBoxWithHeader.setText(_translate("Dialog", "With Header"))
        self.labelDataFileName.setText(_translate("Dialog", "Filename"))
        self.groupBox_2.setTitle(_translate("Dialog", "Predicted Temperature "))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>[<span style=\" vertical-align:super;\">o</span>C]</p></body></html>"))
        self.pushButtonPredict.setText(_translate("Dialog", "Predict"))
        self.labelModelFileName.setText(_translate("Dialog", "Filename"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPredict), _translate("Dialog", "Predict"))
        self.checkBoxShowPerformance.setText(_translate("Dialog", "show Performance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTrain), _translate("Dialog", "Train"))

